sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ajith2234/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ajith2234/react-test npm test

after_success:
  - docker build -t ajith2234/multi-client ./client
  - docker build -t ajith2234/multi-nginx ./nginx
  - docker build -t ajith2234/multi-server ./server
  - docker build -t ajith2234/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ajith2234/multi-client
  - docker push ajith2234/multi-nginx
  - docker push ajith2234/multi-server
  - docker push ajith2234/multi-worker
